version: '3'
services:
  legacy:
    container_name: legacy
    build: .
    image: legacy:latest
    environment:
      - SECRET_KEY=alasldkfjaslkdfklsldkj
      - OMDB_API_KEY=5f8b976a
      - ALT_SEARCH=true
      - ALT_SOURCE=https://imdb.com
      - MYSQL_USER=app
      - MYSQL_PW=dbintegrationtest
      - MYSQL_HOST=db
      - MYSQL_DB=test
      - MYSQL_PORT=3306
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mysql/mysql-server
    container_name: mysql_legacy
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=rootytooty
      - MYSQL_USER=app
      - MYSQL_PASSWORD=dbintegrationtest
      - MYSQL_HOST=localhost
    command: ["mysqld", "--user=root", "--default-authentication-plugin=mysql_native_password"]